#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Lebenslauf.Droid.Resource", IsApplication=true)]

namespace Lebenslauf.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Forms.Platform.Android.Resource.Attribute.actionBarSize = global::Lebenslauf.Droid.Resource.Attribute.actionBarSize;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int A1 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Add = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int contacts = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Del = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int del1 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Del2 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int feedback = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Foto = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int hamburger = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int icon = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Next = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Prev = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int reminders = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int Save = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int Word = 2130837518;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
	}
}
#pragma warning restore 1591
